### PR TITLE
Add `SelectionArea`

### LINKED ISSUE #135: Web版でテキストを選択しコピーなどができるようにする
**Is your feature request related to a problem? Please describe.**
9月7日現在、Web版ではテキストの選択ができません。
イベント情報などをコピーできるように修正した方が良いと思われます。

**Describe the solution you'd like**
Flutterの機能を利用し、テキストを選択できるようにする。

**Describe alternatives you've considered**
none.

**Additional context**
* https://master-api.flutter.dev/flutter/material/SelectionArea-class.html

### PR DESCRIPTION
**Pull request by takassh**
### Description

Wrap `RootScreen` with `SelectionArea` to be able to select texts.

Fixes #135 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Check if text can be select or not on screens.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] My code has been formatted with `flutter format lib` and `flutter pub run import_sorter:main`
- [x] My code has been fixed with `dart fix --apply lib`
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by koji-1009 — APPROVED** [review]
LGTM! Thanks!

**Comment by koji-1009** [comment]
@takassh 
Excuse me. I made a mistake.

With the current implementation, it seems that selection cannot be made on non-root screens such as `licenses/about-us`. Could you investigate this issue?

**Comment by takassh** [comment]
@koji-1009 
It seems `SelectionArea` uses `GestureDetector` to fire selection, so after you move screen, `SelectionArea` is not the ancestor of `AboutUsPage`. See image.
Screenshot 2023-09-12 at 10 46 22

However, we use `ShellRoute` and it includes other routes in its tree. So, we can select texts, for example,`HomePage`.
Screenshot 2023-09-12 at 10 47 53

This forces when we add more pages outside of `SelectionArea` tree, we should wrap the page.

How do you think?

**Comment by koji-1009** [comment]
@takassh 
I have identified the problem. Indeed, it does not seem to work as documente.
How about creating a `Widget` with `Scaffold` + `SelectionArea` as children and replace the `Scaffold` in the app?

```dart
class SelectionAreaScaffold extends StatelessWidget {
  const SelectionScaffold({
    super.key,
    this.appBar,
    this.body,
  });

  final PreferredSizeWidget? appBar;
  final Widget? body;

  @override
  Widget build(BuildContext context) {
    return SelectionArea(
      child: Scaffold(
        appBar: appBar,
        body: body,
      ),
    );
  }
}
```

**Comment by takassh** [comment]
@koji-1009 
sure!
You mean replace all `Scaffold` in the app, right?

**Comment by takassh** [comment]
@koji-1009 
I updated from your suggestion.
I didn't wrap `licenses/legal-notices` with it because it looks we don't need to copy and paste on that page.
Other than the page, copy and paste are working including `licenses/about-us`.

**Review by koji-1009 — APPROVED** [review]
Thanks again! LGTM!

**Pull request merged**
